# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: preview Azure Web App

on:
  push:
    branches:
      - develop
      - "feature/**"
    paths-ignore:
      - "docs/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Remove robots.txt
        run: Remove-Item -Path ./dist/raulschnelzer/robots.txt
        shell: pwsh

      - name: Rename robots.prev.txt to robots.txt
        run: Rename-Item -Path ./dist/raulschnelzer/robots.prev.txt -NewName "robots.txt"
        shell: pwsh

      - name: "Deploy to Azure Preview Slot"
        uses: azure/webapps-deploy@v1
        with:
          app-name: "raulschnelzer"
          slot-name: "raulschnelzer-preview"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_d6e46d4aa8294717a5881065a5ffb548 }}
          package: ./dist/raulschnelzer
