# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: production Azure Web App

on:
  push:
    branches:
      - master
      - 'releases/**'
    paths:
      - "src/**"
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install & build angular
      run: |
        npm install
        npm run build --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'raulschnelzer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d6e46d4aa8294717a5881065a5ffb548 }}
        package: ./dist/raulschnelzer
