name: Nightly Quality Scan

on:
  schedule:
  - cron: "35 0 * * *"
    
jobs:
  sonarCloudTrigger:
  
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    
    steps:
    - uses: workflows/checkout
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
